import { ColorPalette, FontPairing, WebsiteTemplate } from './types';

export const CURATED_PALETTES: ColorPalette[] = [
  {
    id: 'modern-slate',
    name: 'Modern Slate',
    primary: '#2563EB',
    secondary: '#0F172A',
    accent: '#38BDF8',
    background: '#FFFFFF',
    text: '#1E293B',
    vibes: ['modern', 'professional'],
    source: 'curated' as const,
  },
  {
    id: 'clean-mint',
    name: 'Clean Mint',
    primary: '#10B981',
    secondary: '#064E3B',
    accent: '#34D399',
    background: '#F8FAFC',
    text: '#1E293B',
    vibes: ['modern', 'professional'],
    source: 'curated' as const,
  },
  {
    id: 'midnight-tech',
    name: 'Midnight Tech',
    primary: '#6366F1',
    secondary: '#1E1B4B',
    accent: '#A78BFA',
    background: '#FAFAFA',
    text: '#18181B',
    vibes: ['modern', 'bold'],
    source: 'curated' as const,
  },
  {
    id: 'heritage-gold',
    name: 'Heritage Gold',
    primary: '#B45309',
    secondary: '#1C1917',
    accent: '#D97706',
    background: '#FFFBEB',
    text: '#292524',
    vibes: ['classic', 'elegant'],
    source: 'curated' as const,
  },
  {
    id: 'navy-tradition',
    name: 'Navy Tradition',
    primary: '#1E3A5F',
    secondary: '#0C1829',
    accent: '#C8A951',
    background: '#FAFAF9',
    text: '#1C1917',
    vibes: ['classic', 'professional'],
    source: 'curated' as const,
  },
  {
    id: 'warm-earth',
    name: 'Warm Earth',
    primary: '#92400E',
    secondary: '#451A03',
    accent: '#CA8A04',
    background: '#FEF3C7',
    text: '#422006',
    vibes: ['classic'],
    source: 'curated' as const,
  },
  {
    id: 'electric-punch',
    name: 'Electric Punch',
    primary: '#DC2626',
    secondary: '#18181B',
    accent: '#F97316',
    background: '#FFFFFF',
    text: '#18181B',
    vibes: ['bold'],
    source: 'curated' as const,
  },
  {
    id: 'neon-contrast',
    name: 'Neon Contrast',
    primary: '#8B5CF6',
    secondary: '#0F0F0F',
    accent: '#EC4899',
    background: '#FAFAFA',
    text: '#171717',
    vibes: ['bold', 'playful'],
    source: 'curated' as const,
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    primary: '#1D4ED8',
    secondary: '#1E3A5F',
    accent: '#3B82F6',
    background: '#F8FAFC',
    text: '#334155',
    vibes: ['professional'],
    source: 'curated' as const,
  },
  {
    id: 'trust-teal',
    name: 'Trust Teal',
    primary: '#0D9488',
    secondary: '#134E4A',
    accent: '#2DD4BF',
    background: '#FFFFFF',
    text: '#1E293B',
    vibes: ['professional', 'modern'],
    source: 'curated' as const,
  },
  {
    id: 'charcoal-pro',
    name: 'Charcoal Pro',
    primary: '#374151',
    secondary: '#111827',
    accent: '#10B981',
    background: '#F9FAFB',
    text: '#1F2937',
    vibes: ['professional', 'elegant'],
    source: 'curated' as const,
  },
  {
    id: 'sunshine-pop',
    name: 'Sunshine Pop',
    primary: '#F59E0B',
    secondary: '#7C3AED',
    accent: '#EC4899',
    background: '#FFFBEB',
    text: '#1F2937',
    vibes: ['playful'],
    source: 'curated' as const,
  },
  {
    id: 'tropical-burst',
    name: 'Tropical Burst',
    primary: '#06B6D4',
    secondary: '#0E7490',
    accent: '#F97316',
    background: '#F0FDFA',
    text: '#164E63',
    vibes: ['playful', 'modern'],
    source: 'curated' as const,
  },
  {
    id: 'noir-luxe',
    name: 'Noir Luxe',
    primary: '#1C1917',
    secondary: '#292524',
    accent: '#D4A853',
    background: '#FAFAF9',
    text: '#1C1917',
    vibes: ['elegant'],
    source: 'curated' as const,
  },
  {
    id: 'soft-sophisticate',
    name: 'Soft Sophisticate',
    primary: '#78716C',
    secondary: '#292524',
    accent: '#A16207',
    background: '#FAF9F7',
    text: '#44403C',
    vibes: ['elegant', 'classic'],
    source: 'curated' as const,
  },
];

export const CURATED_FONT_PAIRINGS: FontPairing[] = [
  {
    id: 'inter-inter',
    name: 'Clean & Modern',
    heading: 'Inter',
    body: 'Inter',
    vibes: ['modern', 'professional'],
    source: 'curated' as const,
  },
  {
    id: 'montserrat-source',
    name: 'Modern Professional',
    heading: 'Montserrat',
    body: 'Source Sans 3',
    vibes: ['modern', 'professional'],
    source: 'curated' as const,
  },
  {
    id: 'poppins-dm',
    name: 'Friendly Modern',
    heading: 'Poppins',
    body: 'DM Sans',
    vibes: ['modern', 'playful'],
    source: 'curated' as const,
  },
  {
    id: 'raleway-nunito',
    name: 'Soft & Approachable',
    heading: 'Raleway',
    body: 'Nunito Sans',
    vibes: ['modern', 'playful'],
    source: 'curated' as const,
  },
  {
    id: 'playfair-source',
    name: 'Editorial Classic',
    heading: 'Playfair Display',
    body: 'Source Sans 3',
    vibes: ['classic', 'elegant'],
    source: 'curated' as const,
  },
  {
    id: 'merriweather-open',
    name: 'Traditional Authority',
    heading: 'Merriweather',
    body: 'Open Sans',
    vibes: ['classic', 'professional'],
    source: 'curated' as const,
  },
  {
    id: 'lora-nunito',
    name: 'Warm Classic',
    heading: 'Lora',
    body: 'Nunito Sans',
    vibes: ['classic'],
    source: 'curated' as const,
  },
  {
    id: 'montserrat-montserrat',
    name: 'Bold & Uniform',
    heading: 'Montserrat',
    body: 'Montserrat',
    vibes: ['bold', 'modern'],
    source: 'curated' as const,
  },
  {
    id: 'poppins-inter',
    name: 'Bold Impact',
    heading: 'Poppins',
    body: 'Inter',
    vibes: ['bold', 'professional'],
    source: 'curated' as const,
  },
  {
    id: 'dm-inter',
    name: 'Corporate Clean',
    heading: 'DM Sans',
    body: 'Inter',
    vibes: ['professional'],
    source: 'curated' as const,
  },
  {
    id: 'nunito-poppins',
    name: 'Fun & Rounded',
    heading: 'Nunito Sans',
    body: 'Poppins',
    vibes: ['playful'],
    source: 'curated' as const,
  },
  {
    id: 'playfair-dm',
    name: 'Refined Elegance',
    heading: 'Playfair Display',
    body: 'DM Sans',
    vibes: ['elegant'],
    source: 'curated' as const,
  },
];

export const WEBSITE_TEMPLATES: WebsiteTemplate[] = [
  {
    id: 'clean-studio',
    name: 'Clean Studio',
    vibe: 'modern',
    description: 'Clean layouts, minimal details, crisp hierarchy',
    defaultPaletteId: 'modern-slate',
    defaultFontPairingId: 'inter-inter',
  },
  {
    id: 'heritage',
    name: 'Heritage',
    vibe: 'classic',
    description: 'Timeless typography, traditional spacing, refined details',
    defaultPaletteId: 'heritage-gold',
    defaultFontPairingId: 'playfair-source',
  },
  {
    id: 'impact',
    name: 'Impact',
    vibe: 'bold',
    description: 'High contrast, strong headings, confident presentation',
    defaultPaletteId: 'electric-punch',
    defaultFontPairingId: 'poppins-inter',
  },
  {
    id: 'corporate',
    name: 'Corporate',
    vibe: 'professional',
    description: 'Structured, trustworthy, polished business presentation',
    defaultPaletteId: 'corporate-blue',
    defaultFontPairingId: 'dm-inter',
  },
  {
    id: 'bright-and-fun',
    name: 'Bright & Fun',
    vibe: 'playful',
    description: 'Friendly shapes, bright accents, approachable feel',
    defaultPaletteId: 'sunshine-pop',
    defaultFontPairingId: 'nunito-poppins',
  },
  {
    id: 'luxe',
    name: 'Luxe',
    vibe: 'elegant',
    description: 'Refined layouts, generous spacing, premium tone',
    defaultPaletteId: 'noir-luxe',
    defaultFontPairingId: 'playfair-dm',
  },
];

export const VIBE_TOKENS = {
  modern: {
    borderRadius: { sm: '4px', md: '8px', lg: '12px', xl: '16px' },
    shadows: {
      sm: '0 1px 2px rgba(0,0,0,0.05)',
      md: '0 4px 12px rgba(0,0,0,0.08)',
      lg: '0 12px 32px rgba(0,0,0,0.12)',
    },
    spacing: { xs: '4px', sm: '8px', md: '16px', lg: '24px', xl: '32px', '2xl': '48px' },
  },
  classic: {
    borderRadius: { sm: '2px', md: '4px', lg: '6px', xl: '8px' },
    shadows: { sm: '0 1px 3px rgba(0,0,0,0.08)', md: '0 4px 16px rgba(0,0,0,0.1)', lg: '0 16px 48px rgba(0,0,0,0.14)' },
    spacing: { xs: '4px', sm: '8px', md: '16px', lg: '28px', xl: '36px', '2xl': '56px' },
  },
  bold: {
    borderRadius: { sm: '0px', md: '4px', lg: '8px', xl: '12px' },
    shadows: { sm: '0 2px 4px rgba(0,0,0,0.1)', md: '0 8px 24px rgba(0,0,0,0.15)', lg: '0 20px 48px rgba(0,0,0,0.2)' },
    spacing: { xs: '4px', sm: '8px', md: '16px', lg: '24px', xl: '40px', '2xl': '64px' },
  },
  professional: {
    borderRadius: { sm: '4px', md: '6px', lg: '8px', xl: '12px' },
    shadows: { sm: '0 1px 2px rgba(0,0,0,0.06)', md: '0 6px 16px rgba(0,0,0,0.08)', lg: '0 14px 36px rgba(0,0,0,0.1)' },
    spacing: { xs: '4px', sm: '8px', md: '16px', lg: '24px', xl: '32px', '2xl': '48px' },
  },
  playful: {
    borderRadius: { sm: '8px', md: '12px', lg: '20px', xl: '28px' },
    shadows: { sm: '0 2px 6px rgba(0,0,0,0.06)', md: '0 6px 20px rgba(0,0,0,0.1)', lg: '0 16px 40px rgba(0,0,0,0.14)' },
    spacing: { xs: '4px', sm: '10px', md: '18px', lg: '28px', xl: '36px', '2xl': '52px' },
  },
  elegant: {
    borderRadius: { sm: '2px', md: '4px', lg: '8px', xl: '12px' },
    shadows: {
      sm: '0 1px 3px rgba(0,0,0,0.04)',
      md: '0 4px 14px rgba(0,0,0,0.06)',
      lg: '0 12px 36px rgba(0,0,0,0.08)',
    },
    spacing: { xs: '6px', sm: '12px', md: '20px', lg: '32px', xl: '44px', '2xl': '64px' },
  },
} as const;

export type VibeTokens = (typeof VIBE_TOKENS)[keyof typeof VIBE_TOKENS];
