export { ProgressBar } from './progress-bar';
export { Step1Business } from './step-1-business';
export { Step2OnlinePresence } from './step-2-online-presence';
export { Step3Seo } from './step-3-seo';
export { Step4Brand } from './step-4-brand';
export { Step5Content } from './step-5-content';
export { Step6Features } from './step-6-features';
export { Step7Review } from './step-7-review';
// Legacy exports for backward compatibility
export { Step2Brand } from './step-2-brand';
export { Step3Details } from './step-3-details';
export { Step4Domain } from './step-4-domain';
export { Step5Review } from './step-5-review';
